#!/usr/bin/env python3
"""
Test simple rendering with the basic fragment shader.
"""

import sys
sys.path.insert(0, '.')

import numpy as np
import moderngl
import glfw
import time
from engine.gpu import GPUComputePipeline
from engine.shaders import ShaderManager
from engine.camera import Camera

def test_simple_rendering():
    """Test simple rendering with basic fragment shader."""
    print("🔧 Testing Simple Rendering")
    print("=" * 40)
    
    # Create GLFW context
    if not glfw.init():
        raise RuntimeError("Failed to initialize GLFW")
    
    glfw.window_hint(glfw.CONTEXT_VERSION_MAJOR, 4)
    glfw.window_hint(glfw.CONTEXT_VERSION_MINOR, 3)
    glfw.window_hint(glfw.OPENGL_PROFILE, glfw.OPENGL_CORE_PROFILE)
    glfw.window_hint(glfw.OPENGL_FORWARD_COMPAT, True)
    
    window = glfw.create_window(800, 600, "Simple Rendering Test", None, None)
    if not window:
        glfw.terminate()
        raise RuntimeError("Failed to create GLFW window")
    
    glfw.make_context_current(window)
    
    # Create ModernGL context
    ctx = moderngl.create_context()
    
    # Create GPU pipeline
    gpu_pipeline = GPUComputePipeline(ctx)
    
    # Load diagnostic compute shader
    compute_source = open('assets/geodesic_diagnostic.comp', 'r').read()
    gpu_pipeline.create_compute_program(compute_source)
    
    # Load SIMPLE quad shaders (no tone mapping)
    vertex_source = open('assets/quad.vert', 'r').read()
    fragment_source = open('assets/quad_simple.frag', 'r').read()
    gpu_pipeline.create_quad_program(vertex_source, fragment_source)
    
    # Create buffers
    gpu_pipeline.create_buffers()
    
    # Create output texture
    gpu_pipeline.create_output_texture(400, 300)
    
    # Create camera
    camera = Camera(
        radius=5e10,
        azimuth=0.0,
        elevation=np.pi/2.0,
    )
    
    print(f"Camera position: {camera.get_position()}")
    
    # Update camera buffer
    pos = camera.get_position()
    right = np.array([1.0, 0.0, 0.0])
    up = np.array([0.0, 1.0, 0.0])
    forward = np.array([0.0, 0.0, 1.0])
    
    gpu_pipeline.update_camera_ubo(
        position=pos,
        right=right,
        up=up,
        forward=forward,
        tan_half_fov=0.577,
        aspect=4.0/3.0,
        moving=False,
    )
    
    # Dispatch compute shader
    gpu_pipeline.dispatch_compute(400, 300)
    
    # Read back texture data to verify
    texture_data = gpu_pipeline.output_texture.read()
    texture_array = np.frombuffer(texture_data, dtype=np.uint8)
    texture_array = texture_array.reshape((300, 400, 4))
    
    non_black_pixels = np.any(texture_array != 0, axis=2)
    num_non_black = np.sum(non_black_pixels)
    print(f"Non-black pixels: {num_non_black} / {400*300}")
    
    if num_non_black == 0:
        print("❌ No pixels generated by compute shader")
        return False
    
    # Render to screen
    print("Rendering to screen with simple fragment shader...")
    ctx.viewport = (0, 0, 800, 600)
    ctx.clear(0.0, 0.0, 0.0, 1.0)
    
    # Disable depth test
    ctx.disable(moderngl.DEPTH_TEST)
    
    # Render quad
    gpu_pipeline.render_quad()
    glfw.swap_buffers(window)
    
    print("You should now see:")
    print("- A colorful gradient background")
    print("- A red circle in the center")
    print("- Some noise/texture")
    print("Press ESC to exit...")
    
    # Keep window open
    start_time = time.time()
    while not glfw.window_should_close(window):
        glfw.poll_events()
        if glfw.get_key(window, glfw.KEY_ESCAPE) == glfw.PRESS:
            break
        if time.time() - start_time > 5.0:  # Auto-close after 5 seconds
            break
    
    # Cleanup
    gpu_pipeline.cleanup()
    glfw.destroy_window(window)
    glfw.terminate()
    print("✅ Cleanup completed")
    return True

if __name__ == "__main__":
    test_simple_rendering()
